---
#single pod with multiple container's
apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pods
  namespace: lucifer
  labels:
    app: httpd
    tier: frontend-backend
    version: v1
spec:
  containers:
  - name: web
    image: httpd
    ports:
    - containerPort: 80
  - name: db
    image: postgres
    ports:
    - containerPort: 5432
