---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: lucifer
  labels:
    role: web-service
spec:
  selector:
    role: webserver
    # version: 'v3'
    tier: frond
    jane: akil
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
