---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-pv-claim
  labels:
    app: webserver
spec:
  accessModes:
    - ReadOnlyMany
    #- ReadWriteMany
    #- ReadWriteOnce
  storageClassName:  ssd
  resources:
    requests:
      storage: 10Gi
