apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: nginx
    tier: front
    version: v1
    env: production
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: webdata
      mountPath: /usr/share/nginx/html
  volumes:
  - name: webdata
    persistentVolumeClaim:
      claimName: wp-pv-claim

