---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: lucifer
spec:
  strategy:
    type: RollingUpdate #Bydefault (RollingUpdate/Recreate)
  revisionHistoryLimit: 4
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      role: cache-server
  template:
    metadata:
      name: web
      labels:
        role: cache-server
    spec:
      containers:
      - name: redis-server
        image: redis
        ports:
        - containerPort: 6379
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: lucifer
  labels:
    role: redis-service
spec:
  selector:
    role: cache-server
  type: ClusterIP
  ports:
  - port: 6379
