apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jinojoe@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik


---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: check.jino.in
spec:
  secretName: check.jino.in
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
  commonName: check.jino.in
  dnsNames:
    - check.jino.in
  acme:
    config:
      - http01:
          ingressClass: traefik
        domains:
          - check.jino.in
