global:
  slack_api_url: 'https://hooks.slack.com/services/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f7rM' # change ur slack value
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 10m
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#anisble'   # Please change your channel
    icon_emoji: ':bell:'
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.message }}\n"

# kubectl get secret alertmanager-moniter-prometheus-operato-alertmanager -o json
# echo Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KcmVjZWl2ZXJzOgotIG5hbWU6ICJudWxsIgpyb3V0ZToKICBncm91cF9ieToKICAtIGpvYgogIGdyb3VwX2ludGVydmFsOiA1bQogIGdyb3VwX3dhaXQ6IDMwcwogIHJlY2VpdmVyOiAibnVsbCIKICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJvdXRlczoKICAtIG1hdGNoOgogICAgICBhbGVydG5hbWU6IFdhdGNoZG9nCiAgICByZWNlaXZlcjogIm51bGwiCg== | bas64 -d
# kubectl delete secret alertmanager-moniter-prometheus-operato-alertmanager
# kubectl create secret generic alertmanager-moniter-prometheus-operato-alertmanager --from-file=alertmanager.yaml
