---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: facebook
spec:
  strategy:
    type: RollingUpdate #Bydefault (RollingUpdate/Recreate)
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      role: web-service
  template:
    metadata:
      name: web
      labels:
        role: web-service
    spec:
      containers:
      - name: web
        image: jjino/env
        env:
          - name: OPTION_A
            valueFrom:
              secretKeyRef:
                name: secrets
                key: OPTION_A
          - name: OPTION_B
            valueFrom:
              secretKeyRef:
                name: secrets
                key: OPTION_B
        ports:
        - containerPort: 80
          protocol: TCP
